-- Enable RLS (Row Level Security) generally, but we will create policies
-- However, for simplicity in this setup, we sometimes disable RLS or create permissive policies.

-- 1. Create table for Authorized Persons (Installers/SuperAdmins)
create table if not exists public.authorized_persons (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  names text not null,
  passwords text not null
);

-- Fix: Add 'role' column if it doesn't exist (SAFE TO RUN on existing table)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='authorized_persons' AND column_name='role') THEN
        ALTER TABLE public.authorized_persons ADD COLUMN role text DEFAULT 'installer';
    END IF;
END $$;

-- Insert a default super admin
-- The user asked for "secure_Sys_2026!" but you must add it yourself manually or via this script.
insert into public.authorized_persons (names, passwords, role)
values ('superadmin', 'secure_Sys_2026!', 'superadmin')
ON CONFLICT DO NOTHING; -- Avoid duplicate errors if run multiple times


-- 2. Create table for Installations (License/Contract tracking)
create table if not exists public.installations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  system_id text not null unique,
  pc_name text,
  serial_key text,
  company_name text,
  phone text,
  email text,
  address text,
  location text,
  license text,
  status text default 'active', -- 'active', 'deactivated'
  installation_time text,
  installed_by text,
  contract_duration_days int,
  contract_expiry text, -- 'YYYY-MM-DD'
  needs_renewal_notification boolean default false
);

-- 3. Create table for Client Accounts (Store Owners/Managers)
create table if not exists public."CLIENT_NAME_PASSWORD" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  names text not null,
  passwords text not null
);

-- 4. Enable RLS (Optional - if you want security)
alter table public.authorized_persons enable row level security;
alter table public.installations enable row level security;
alter table public."CLIENT_NAME_PASSWORD" enable row level security;

-- 5. Create Policies (Allow Public Read/Write for these specific POS requirements)
-- In a real production environment, you might want tighter security, 
-- but for this standalone POS to work simply:

-- Authorized Persons: Allow Read (for login)
create policy "Enable read access for all users" on public.authorized_persons
for select using (true);

-- Installations: Allow Read/Insert/Update (for registration and status checks)
create policy "Enable read access for all users" on public.installations
for select using (true);

create policy "Enable insert for all users" on public.installations
for insert with check (true);

create policy "Enable update for all users" on public.installations
for update using (true);

-- Client Name Password: Allow Read/Insert
create policy "Enable read access for all users" on public."CLIENT_NAME_PASSWORD"
for select using (true);

create policy "Enable insert for all users" on public."CLIENT_NAME_PASSWORD"
for insert with check (true);
