from PyQt6.QtCore import QObject, pyqtSignal
import json
import os

class Localization(QObject):
    language_changed = pyqtSignal(str)
    _instance = None
    
    def __init__(self):
        super().__init__()
        self.current_lang = "en"
        self.translations = {
            "en": {
                "welcome_title":"Welcome",
                "select_business":"Select a business to continue",
                "login": "Login",
                "username": "Username",
                "password": "Password",
                "sales": "Sales",
                "inventory": "Inventory",
                "customers": "Customers",
                "suppliers": "Suppliers",
                "loans": "Loans",
                "reports": "Reports",
                "settings": "Settings",
                "logout": "Logout",
                "product_name": "Product Name",
                "barcode": "Barcode",
                "price": "Price",
                "quantity": "Quantity",
                "total": "Total",
                "add": "Add",
                "edit": "Edit",
                "delete": "Delete",
                "save": "Save",
                "cancel": "Cancel",
                "search": "Search",
                "print": "Print",
                "checkout": "Checkout",
                "discount": "Discount",
                "cash": "Cash",
                "credit": "Credit",
                "back": "Back",
                "admin": "Admin",
                "cashier": "Cashier",
                "low_stock": "Low Stock",
                "price_check": "Price Check",
                "returns": "Returns",
                "pharmacy": "Pharmacy",
                "store": "General Store",
                "dashboard": "Dashboard",
                "finance": "Finance",
                "users": "Users",
                "pharm_dashboard": "Ph-Dashboard",
                "pharm_finance": "Ph-Finance",
                "pharm_inventory": "Ph-Inventory",
                "pharm_sales": "Ph-Sales",
                "pharm_customers": "Ph-Customers",
                "pharm_suppliers": "Ph-Suppliers",
                "pharm_loans": "Ph-Loan",
                "pharm_reports": "Ph-Reports",
                "pharm_price_check": "Ph-PriceCheck",
                "pharm_returns": "Ph-Returns",
                "pharm_users": "Ph-Users",
                "pharm_settings": "Ph-Settings",
                # Dashboard Cards
                "pharmacy_finance": "Pharmacy Finance",
                "credit_controls": "Credit Controls",
                "user_management": "User Management",
                "inventory_stats": "Inventory Statistics",
                "select_product_info": "Select a product to view stats",
                # Common UI
                "name": "Name",
                "phone": "Phone",
                "address": "Address",
                "email": "Email",
                "date": "Date",
                "status": "Status",
                "actions": "Actions",
                "amount": "Amount",
                "balance": "Balance",
                "paid": "Paid",
                "pending": "Pending",
                "type": "Type",
                "notes": "Notes",
                "description": "Description",
                "category": "Category",
                "batch_number": "Batch #",
                "expiry_date": "Expiry Date",
                "purchase_price": "Purchase Price",
                "sale_price": "Sale Price",
                "stock": "Stock",
                "unit": "Unit",
                "medicine": "Medicine",
                "days_left": "Days Left",
                # Buttons
                "add_new": "Add New",
                "refresh": "Refresh",
                "clear": "Clear",
                "submit": "Submit",
                "confirm": "Confirm",
                "close": "Close",
                "view": "View",
                "details": "Details",
                "process": "Process",
                "pay": "Pay",
                "receive": "Receive",
                "return": "Return",
                "reprint": "Reprint",
                # Finance
                "daily_report": "Daily Report",
                "monthly_report": "Monthly Report",
                "yearly_report": "Yearly Report",
                "overview": "Overview",
                "income": "Income",
                "expenses": "Expenses",
                "profit": "Profit",
                "net_profit": "Net Profit",
                "gross_sales": "Gross Sales",
                "total_sales": "Total Sales",
                "total_orders": "Total Orders",
                "total_returns": "Total Returns",
                "cash_received": "Cash Received",
                "credit_given": "Credit Given",
                # Inventory
                "add_product": "Add Product",
                "edit_product": "Edit Product",
                "low_stock_alert": "Low Stock Alert",
                "out_of_stock": "Out of Stock",
                "in_stock": "In Stock",
                "reorder_level": "Reorder Level",
                # Sales
                "new_sale": "New Sale",
                "cart": "Cart",
                "subtotal": "Subtotal",
                "grand_total": "Grand Total",
                "payment_method": "Payment Method",
                "customer": "Customer",
                "walk_in": "Walk-in",
                "bill_number": "Bill #",
                "invoice": "Invoice",
                # Customers/Suppliers
                "add_customer": "Add Customer",
                "add_supplier": "Add Supplier",
                "customer_name": "Customer Name",
                "supplier_name": "Supplier Name",
                "contact": "Contact",
                "total_purchases": "Total Purchases",
                "total_due": "Total Due",
                # Loans
                "give_loan": "Give Loan",
                "receive_payment": "Receive Payment",
                "loan_history": "Loan History",
                "outstanding": "Outstanding",
                "loan_date": "Loan Date",
                "due_date": "Due Date",
                # Reports
                "sales_report": "Sales Report",
                "inventory_report": "Inventory Report",
                "customer_report": "Customer Report",
                "expiry_report": "Expiry Report",
                "expiring_stock": "Expiring Stock",
                "expired": "EXPIRED",
                "alert": "ALERT",
                "active": "ACTIVE",
                "print_report": "Print Report",
                "net_sales": "Net Sales",
                "return_items_count": "Return Items",
                "transaction_details": "Transaction Details",
                "returned_items_details": "Returned Items Details",
                "credit_loan_info": "Credit & Loan Information",
                "low_stock_medicines": "Low Stock Medicines",
                "medicine_expiry_status": "Medicine Expiry Status",
                "print_transactions": "🖨️ Print Transactions",
                "print_loans": "🖨️ Print Loans",
                "print_stock_report": "🖨️ Print Stock Report",
                "print_expiry_report": "🖨️ Print Expiry Report",
                "print_returns": "🖨️ Print Returns Report",
                "print_complete_pharmacy_report": "🖨️ Print Complete Pharmacy Report",
                "last_7_days": "Last 7 Days",
                "this_month": "This Month",
                "today": "Today",
                "expiring_within": "Expiring within",
                "days": "Days",
                "invoice_number_short": "Inv #",
                "batch_no_short": "Batch #",
                "invoices_transactions": "Invoices / Transactions",
                "pharmacy_loans_credit_details": "Pharmacy Loans / Credit Details",
                "critical_stock_alert": "Critical Stock Alert",
                "expiring_stock_report": "Expiring Stock Report",
                "showing_items_expiring_within": "Showing items expiring within:",
                "report_period": "Report Period",
                "generated_at": "Generated",
                "total_active_loans": "Total Active Loans",
                "total_loan_amount": "Total Loan Amount",
                "total_outstanding_balance": "Total Outstanding Balance",
                "total_items_monitored": "Total Items Monitored",
                "already_expired_count": "Already Expired",
                "nearing_expiry": "Nearing Expiry",
                "total_transactions": "Total Transactions",
                "total_items_sold": "Total Items Sold",
                "total_sales_amount": "Total Sales Amount",
                "total_low_stock_items": "Total Low Stock Items",
                "complete_pharmacy_reports_summary": "Complete Pharmacy Reports Summary",
                # Settings
                "company_info": "Company Info",
                "maintenance": "Maintenance",
                "backup": "Backup",
                "restore": "Restore",
                "company_name": "Company Name",
                "company_address": "Company Address",
                "company_phone": "Company Phone",
                "language": "Language",
                "theme": "Theme",
                "dark_mode": "Dark Mode",
                "light_mode": "Light Mode",
                # Users
                "role": "Role",
                "permissions": "Permissions",
                "add_user": "Add User",
                "edit_user": "Edit User",
                "manager": "Manager",
                "staff": "Staff",
                # Returns
                "return_item": "Return Item",
                "return_reason": "Return Reason",
                "refund_amount": "Refund Amount",
                "original_bill": "Original Bill",
                # Messages
                "success": "Success",
                "error": "Error",
                "warning": "Warning",
                "confirm_delete": "Confirm Delete",
                "no_data": "No Data",
                "loading": "Loading...",
                "customer_not_found": "Customer details not found",
                "payment_received": "Payment received successfully",
                "required": "Required",
                "and": "and",
                "name_contact_required": "Name and Contact are required",
                 "confirm_delete_supplier": "Are you sure you want to delete this supplier?",
                 "remove": "Remove",
                 "confirm_remove_salary": "Remove this salary configuration?",
                 "main_finance_notice": "Salary assignment for main system users should be done from the main Finance module.",
                 "custom_range": "Custom Range",
                 "reprint_bill": "Reprint Bill",
                 "weekly_report": "Weekly Report",
                 "weekly": "Weekly",
                 "units": "Units",
                 "enter_reason": "Enter Reason",
                 "reason": "Reason",
                 "select_quantity": "Please select a quantity",
                 "account": "Account",
                 "refund_mode": "Refund Mode",
                # Added Detailed Pharmacy Keys
                "pharmacy_financial_management": "Pharmacy Financial Management",
                "record_new_expense": "Record New Expense / Petty Cash",
                "daily_expense": "Daily Expense",
                "petty_cash": "Petty Cash",
                "utility": "Utility",
                "other": "Other",
                "description_of_expense": "Description of expense",
                "daily_total": "Daily Total",
                "monthly_total": "Monthly Total",
                "staff_salary_setup": "Staff Salary Setup",
                "select_staff": "Select Staff",
                "salary_type": "Salary Type",
                "assign_salary": "Assign Salary",
                "staff_name": "Staff Name",
                "salary_configured_success": "Salary configured successfully",
                "gross_cogs": "Gross COGS",
                "net_cogs": "Net COGS",
                "trading_profit": "Trading Profit",
                "opex": "Total OpEx",
                "net_monthly_profit": "Net Monthly Profit",
                "total_val": "Total Val",
                "cost": "Cost",
                "brand": "Brand",
                "company": "Company",
                "vendor": "Vendor",
                "add_medicine": "Add Medicine",
                "basket": "Basket",
                "last_bill": "Last Bill #",
                "reprint_last_bill": "Reprint Last Bill",
                "method": "Method",
                "credit_sale_loan": "Credit Sale (Loan)",
                "process_checkout": "Process Checkout",
                "walk_in_customer": "Walk-in Customer",
                "insufficient_stock": "Insufficient Stock",
                "limit_exceeded": "Limit Exceeded",
                "customer_info": "Customer Information",
                "kyc_management": "Pharmacy Customer Management & KYC",
                "basic_info": "Basic Information",
                "contact_number": "Contact Number",
                "allow_credit_sales": "Allow Credit Sales",
                "kyc_documentation": "KYC Documentation",
                "customer_photo": "Customer Photo",
                "id_card_photo": "ID Card Photo",
                "browse": "Browse",
                "upload_method": "Upload Method",
                "open_camera": "Open Camera",
                "upload_photo": "Upload Photo",
                "add_edit_supplier": "Add / Edit Pharmacy Supplier",
                "monthly_close": "Month-End Close",
                "preset": "Preset",
                "from": "From",
                "to": "To",
                "price_check_placeholder": "Scan an item to see price and stock",
                "not_found": "Product Not Found",
                "already_returned": "Already Ret",
                "remaining": "Remaining",
                "refund_mode": "Refund Mode",
                "fully_returned": "Fully Returned",
                "show_passwords": "Show Passwords",
                "hide_passwords": "Hide Passwords",
                "assigned_features": "Assigned Features",
                "whatsapp_integration": "WhatsApp Integration",
                "offline_mode": "Enable Offline Mode",
                "optimize_database": "Optimize Database",
                "clear_logs": "Clear Activity Logs",
                "full_backup": "Create Full Backup",
                "restore_backup": "Restore from Backup",
                # Replacement Items & Returns
                "replacement_items": "Replacement Items",
                "select_replacement_items": "Select Replacement Items",
                "selected_items": "Selected Items",
                "return_value": "Return Value",
                "replacement_value": "Replacement Value",
                "replacement_value_mismatch": "Replacement value does not match return value",
                "continue": "Continue",
                "action": "Action",
                "invoice_not_found": "Invoice not found",
                "for": "for",
                "product": "Product",
                "return_quantity": "Return Quantity",
                "camera_error": "Camera Error",
                "resumed": "Resumed",
                "sale_transaction_resumed": "Sale transaction resumed.",
                "invalid_qty": "Invalid Qty",
                "qty_cannot_be_negative": "Quantity cannot be negative.",
                "sale_completed": "Sale completed",
                "bill_printed_successfully": "Bill printed successfully!",
                "print_error": "Print Error",
                "failed_to_generate_bill": "Failed to generate bill.",
                "failed_to_print_bill": "Failed to print bill",
                "no_bills": "No Bills",
                "no_bills_found_to_reprint": "No bills found to reprint",
                "no_records": "No Records",
                "no_kyc_found": "No KYC documents found for this customer.",
                "successfully_returned": "Successfully returned",
                "items": "items",
                "refund": "Refund",
                "no_sale_found_with_invoice": "No sale found with invoice",
                "ready_to_scan": "READY TO SCAN",
                "scan": "Scan"
            },
            "ps": {
                "welcome_title":"ښه راغلاست",
                "select_business":"خپل کاروبار وټاکئ",
                "login": "ننووتل",
                "username": "کارن نوم",
                "password": "پټنوم",
                "sales": "پلور",
                "inventory": "ګودام",
                "customers": "پېرودونکي",
                "suppliers": "برابروونکي",
                "loans": "پورونه",
                "reports": "راپورونه",
                "settings": "تنظیمات",
                "logout": "وتل",
                "product_name": "د توکي نوم",
                "barcode": "بارکوډ",
                "price": "بیه",
                "quantity": "شمېر",
                "total": "ټول",
                "add": "زیاتول",
                "edit": "سمون",
                "delete": "له منځه وړل",
                "save": "ساتل",
                "cancel": "بندول",
                "search": "لټون",
                "print": "چاپ",
                "checkout": "تادیه",
                "discount": "تخفیف",
                "cash": "نغدې",
                "credit": "پور",
                "back": "شاته",
                "admin": "اډمین",
                "cashier": "کاشیر",
                "low_stock": "کم ذخیره",
                "price_check": "نرخ کتل",
                "returns": "ګرځول شوي توکي",
                "pharmacy": "درملتون",
                "store": "خوراکه فروشي",
                "dashboard": "ډشبورډ",
                "finance": "مالي",
                "users": "کارونکي",
                "pharm_dashboard": "ډشبورډ",
                "pharm_finance": "مالي",
                "pharm_inventory": "ګودام",
                "pharm_sales": "پلور",
                "pharm_customers": "پېرودونکي",
                "pharm_suppliers": "برابروونکي",
                "pharm_loans": "قرضې",
                "pharm_reports": "راپورونه",
                "pharm_price_check": "نرخ",
                "pharm_returns": "ګرځول",
                "pharm_users": "کارونکي",
                "pharm_settings": "تنظیمات",
                # Dashboard Cards
                "pharmacy_finance": "مالي درملتون",
                "credit_controls": "د پور کنټرول",
                "user_management": "د کارونکو مدیریت",
                "inventory_stats": "د ګودام ارقام",
                "select_product_info": "د معلوماتو لپاره توکی وټاکئ",
                # Common UI
                "name": "نوم",
                "phone": "تلیفون",
                "address": "پته",
                "email": "بریښنالیک",
                "date": "نېټه",
                "status": "حالت",
                "actions": "عملونه",
                "amount": "مقدار",
                "balance": "بیلانس",
                "paid": "ورکړل شوی",
                "pending": "پاتې",
                "type": "ډول",
                "notes": "یادونې",
                "description": "توضیحات",
                "category": "کټګوري",
                "batch_number": "بیچ #",
                "expiry_date": "د ختمېدو نېټه",
                "purchase_price": "د اخیستلو بیه",
                "sale_price": "د پلور بیه",
                "stock": "ذخیره",
                "unit": "واحد",
                "medicine": "درمل",
                "days_left": "پاتې ورځې",
                # Buttons
                "add_new": "نوی زیاتول",
                "refresh": "تازه کول",
                "clear": "پاکول",
                "submit": "لېږل",
                "confirm": "تایید",
                "close": "بندول",
                "view": "لیدل",
                "details": "جزئیات",
                "process": "پروسس",
                "pay": "تادیه",
                "receive": "ترلاسه کول",
                "return": "بېرته ورکول",
                "reprint": "بیا چاپ",
                # Finance
                "daily_report": "ورځنی راپور",
                "monthly_report": "میاشتنی راپور",
                "yearly_report": "کلنی راپور",
                "overview": "لنډیز",
                "income": "عاید",
                "expenses": "لګښتونه",
                "profit": "ګټه",
                "net_profit": "خالصه ګټه",
                "gross_sales": "ټول پلور",
                "total_sales": "ټول پلور",
                "total_orders": "ټول آرډرونه",
                "total_returns": "ټول بېرته ورکول",
                "cash_received": "نغدې ترلاسه شوې",
                "credit_given": "ورکړل شوی پور",
                # Inventory
                "add_product": "توکی زیاتول",
                "edit_product": "توکی سمول",
                "low_stock_alert": "کم ذخیره خبرتیا",
                "out_of_stock": "ذخیره پای ته رسېدلې",
                "in_stock": "شتون لري",
                "reorder_level": "بیا آرډر کچه",
                # Sales
                "new_sale": "نوی پلور",
                "cart": "کارټ",
                "subtotal": "فرعي مجموعه",
                "grand_total": "لویه مجموعه",
                "payment_method": "د تادیې طریقه",
                "customer": "پېرودونکی",
                "walk_in": "مستقیم",
                "bill_number": "بل #",
                "invoice": "رسید",
                # Customers/Suppliers
                "add_customer": "پېرودونکی زیاتول",
                "add_supplier": "برابروونکی زیاتول",
                "customer_name": "د پېرودونکي نوم",
                "supplier_name": "د برابروونکي نوم",
                "contact": "اړیکه",
                "total_purchases": "ټول اخیستنې",
                "total_due": "ټول پور",
                # Loans
                "give_loan": "پور ورکول",
                "receive_payment": "تادیه ترلاسه کول",
                "loan_history": "د پور تاریخچه",
                "outstanding": "پاتې پور",
                "loan_date": "د پور نېټه",
                "due_date": "د ختمېدو نېټه",
                # Reports
                "sales_report": "د پلور راپور",
                "inventory_report": "د ګودام راپور",
                "customer_report": "د پېرودونکو راپور",
                "expiry_report": "د ختمېدو راپور",
                "expiring_stock": "ختمېدونکی ذخیره",
                "expired": "ختم شوی",
                "alert": "خبرتیا",
                "active": "فعال",
                "print_report": "راپور چاپول",
                "net_sales": "خالص پلور",
                "return_items_count": "بېرته شوي توکي",
                "transaction_details": "د راکړې ورکړې جزیات",
                "returned_items_details": "د بېرته شوو توکو جزیات",
                "credit_loan_info": "د پورونو معلومات",
                "low_stock_medicines": "د کمو درملو لست",
                "medicine_expiry_status": "د درملو د ختمېدو حالت",
                "print_transactions": "🖨️ لیږدونه چاپول",
                "print_loans": "🖨️ پورونه چاپول",
                "print_stock_report": "🖨️ سټاک راپور چاپول",
                "print_expiry_report": "🖨️ د ختمیدو راپور",
                "print_returns": "🖨️ د بېرته شوو راپور چاپول",
                "print_complete_pharmacy_report": "🖨️ بشپړ راپور چاپول",
                "last_7_days": "تېرې ۷ ورځې",
                "this_month": "دا میاشت",
                "today": "نن",
                "expiring_within": "ختمېدونکی په",
                "days": "ورځې",
                "invoice_number_short": "بل شمېره",
                "batch_no_short": "بچ شمېره",
                "invoices_transactions": "بلونه / معاملې",
                "pharmacy_loans_credit_details": "د درملتون د پورونو تفصیل",
                "critical_stock_alert": "د سټاک مهمه خبرتیا",
                "expiring_stock_report": "د ختمیدونکي سټاک راپور",
                "showing_items_expiring_within": "د هغو توکو ښودل چې ختمېږي په:",
                "report_period": "د راپور موده",
                "generated_at": "جوړ شوی",
                "total_active_loans": "ټول فعال پورونه",
                "total_loan_amount": "د پور مجموعي مبلغ",
                "total_outstanding_balance": "پاتې مجموعه",
                "total_items_monitored": "ټول څارل شوي توکي",
                "already_expired_count": "مخکې ختم شوي",
                "nearing_expiry": "ختمېدو ته نږدې",
                "total_transactions": "ټولې معاملې",
                "total_items_sold": "ټول پلورل شوي توکي",
                "total_sales_amount": "د پلور مجموعي مبلغ",
                "total_low_stock_items": "د کم سټاک توکي ټول مجموعه",
                "complete_pharmacy_reports_summary": "د درملتون د راپورونو بشپړه خلاصه",
                # Settings
                "company_info": "د شرکت معلومات",
                "maintenance": "ساتنه",
                "backup": "بیک اپ",
                "restore": "بیرته راوستل",
                "company_name": "د شرکت نوم",
                "company_address": "د شرکت پته",
                "company_phone": "د شرکت تلیفون",
                "language": "ژبه",
                "theme": "ظاهر",
                "dark_mode": "تیاره حالت",
                "light_mode": "روښانه حالت",
                # Users
                "role": "رول",
                "permissions": "اجازې",
                "add_user": "کارونکی زیاتول",
                "edit_user": "کارونکی سمول",
                "manager": "مدیر",
                "staff": "کارمند",
                # Returns
                "return_item": "توکی بېرته ورکول",
                "return_reason": "د بېرته ورکولو دلیل",
                "refund_amount": "بېرته پیسې",
                "original_bill": "اصلي بل",
                # Messages
                "success": "بریالی",
                "error": "تېروتنه",
                "warning": "خبرتیا",
                "confirm_delete": "د لیرې کولو تایید",
                "no_data": "معلومات نشته",
                "loading": "لوډېږي...",
                "customer_not_found": "د پېرودونکي معلومات ونه موندل شول",
                "payment_received": "تادیه په بریالیتوب سره ترلاسه شوه",
                "required": "اړین",
                "and": "او",
                "name_contact_required": "نوم او اړیکه اړین دي",
                 "confirm_delete_supplier": "ایا تاسو ډاډه یاست چې دا برابروونکی حذف کړئ؟",
                 "remove": "لرې کول",
                 "confirm_remove_salary": "ایا تاسو غواړئ دا معاش ترتیب لرې کړئ؟",
                 "main_finance_notice": "د اصلي سیسټم کاروونکو لپاره د معاش ټاکل باید په اصلي مالي برخه کې ترسره شي.",
                 "custom_range": "ټاکل شوې موده",
                 "reprint_bill": "بل بیا چاپول",
                 "weekly_report": "اوونیز راپور",
                 "weekly": "اوونیز",
                 "units": "واحدونه",
                 "enter_reason": "دلیل ولیکئ",
                 "reason": "دلیل",
                 "select_quantity": "مهرباني وکړئ مقدار وټاکئ",
                 "account": "حساب",
                 "refund_mode": "د بېرته ورکولو ډول",
                # Added Detailed Pharmacy Keys
                "pharmacy_financial_management": "د درملتون مالي مدیریت",
                "record_new_expense": "د نوي لګښت ثبتول",
                "daily_expense": "ورځنی لګښت",
                "petty_cash": "کوچنۍ نغدې",
                "utility": "خدمات",
                "other": "نور",
                "description_of_expense": "د لګښت تفصیل",
                "daily_total": "ورځنۍ مجموعه",
                "monthly_total": "میاشتنۍ مجموعه",
                "staff_salary_setup": "د کارمندانو معاش ترتیب",
                "select_staff": "کارمند غوره کړئ",
                "salary_type": "د معاش ډول",
                "assign_salary": "معاش ټاکل",
                "staff_name": "د کارمند نوم",
                "salary_configured_success": "معاش په بریالیتوب سره تنظیم شو",
                "gross_cogs": "ناخالصه COGS",
                "net_cogs": "خالصه COGS",
                "trading_profit": "سوداګریزه ګټه",
                "opex": "ټول عملیاتي لګښتونه",
                "net_monthly_profit": "خالصه میاشتنۍ ګټه",
                "total_val": "ټول ارزښت",
                "cost": "قیمت",
                "brand": "برانډ",
                "company": "شرکت",
                "vendor": "پلورونکی",
                "add_medicine": "درمل زیاتول",
                "basket": "کڅوړه",
                "last_bill": "وروستی بل #",
                "reprint_last_bill": "بل بیا چاپول",
                "method": "طریقه",
                "credit_sale_loan": "د پور پلور",
                "process_checkout": "تادیه کول",
                "walk_in_customer": "عادي پېرودونکی",
                "insufficient_stock": "کمه ذخیره",
                "limit_exceeded": "لیمیټ ته ورسېد",
                "customer_info": "د پېرودونکي معلومات",
                "kyc_management": "د پېرودونکي پیژندنه او مدیریت",
                "basic_info": "بنسټیز معلومات",
                "contact_number": "د اړیکې شمیره",
                "allow_credit_sales": "د پور پلور اجازه",
                "kyc_documentation": "KYC اسناد",
                "customer_photo": "د پېرودونکي عکس",
                "id_card_photo": "د پیژندپاڼې عکس",
                "browse": "پلټل",
                "upload_method": "د اپلوډ طریقه",
                "open_camera": "کیمره خلاصول",
                "upload_photo": "عکس اپلوډ کول",
                "add_edit_supplier": "د برابروونکي زیاتول یا سمول",
                "monthly_close": "د میاشتې پای بندول",
                "preset": "مخکینۍ بڼه",
                "from": "له",
                "to": "تر",
                "price_check_placeholder": "د نرخ او ذخیرې لیدلو لپاره توکی سکین کړئ",
                "not_found": "توکی ونه موندل شو",
                "already_returned": "مخکې ګرځول شوی",
                "remaining": "پاتې",
                "refund_mode": "د بېرته ورکولو ډول",
                "fully_returned": "بشپړ ګرځول شوی",
                "show_passwords": "پټنوم ښودل",
                "hide_passwords": "پټنوم پټول",
                "assigned_features": "ټاکل شوې برخې",
                "whatsapp_integration": "واټساپ سره ونښلول",
                "offline_mode": "افلاین حالت فعالول",
                "optimize_database": "ډیټابیس اصلاح کول",
                "clear_logs": "لاګونه پاکول",
                "full_backup": "بشپړ بیک اپ اخیستل",
                "invoice_not_found": "رسید ونه موندل شو",
                "for": "لپاره",
                "product": "توکی",
                "return_quantity": "د بېرته ورکولو مقدار",
                "camera_error": "کیمره کې ستونزه",
                "resumed": "بیا پیل شو",
                "sale_transaction_resumed": "د پلور معامله بیا پیل شوه.",
                "invalid_qty": "ناسم مقدار",
                "qty_cannot_be_negative": "مقدار منفي نشي کیدی.",
                "sale_completed": "پلور بشپړ شو",
                "bill_printed_successfully": "بل په بریالیتوب سره چاپ شو!",
                "print_error": "د چاپ تېروتنه",
                "failed_to_generate_bill": "د بل په جوړولو کې ستونزه.",
                "failed_to_print_bill": "د بل په چاپ کې ستونزه",
                "no_bills": "بلونه نشته",
                "no_bills_found_to_reprint": "د بیا چاپ لپاره بل ونه موندل شو",
                "no_records": "ریکارډونه نشته",
                "no_kyc_found": "د دې پېرودونکي لپاره اسناد ونه موندل شول.",
                "successfully_returned": "په بریالیتوب سره بېرته شو",
                "items": "توکي",
                "refund": "بېرته پیسې",
                "no_sale_found_with_invoice": "دې رسید سره پلور ونه موندل شو",
                "ready_to_scan": "سکین ته چمتو",
                "scan": "سکین"
            },
            "dr": {
                "welcome_title":"خوش آمدید",
                "select_business":"تجارت خود را انتخاب کنید",
                "login": "ورود",
                "username": "نام کاربری",
                "password": "رمز عبور",
                "sales": "فروش",
                "inventory": "موجودی",
                "customers": "مشتریان",
                "suppliers": "تامین کنندگان",
                "loans": "قرضه‌ها",
                "reports": "گزارش‌ها",
                "settings": "تنظیمات",
                "logout": "خروج",
                "product_name": "نام محصول",
                "barcode": "بارکد",
                "price": "قیمت",
                "quantity": "تعداد",
                "total": "مجموع",
                "add": "افزودن",
                "edit": "ویرایش",
                "delete": "حذف",
                "save": "ذخیره",
                "cancel": "لغو",
                "search": "جستجو",
                "print": "چاپ",
                "checkout": "پرداخت",
                "discount": "تخفیف",
                "cash": "نقد",
                "credit": "قرضه",
                "back": "بازگشت",
                "admin": "ادمین",
                "cashier": "کاشیر",
                "low_stock": "کمبود موجودی",
                "price_check": "بررسی قیمت",
                "returns": "کالاهای مرجوعی",
                "pharmacy": "داروخانه",
                "store": "خوراکه فروشی",
                "dashboard": "داشبورد",
                "finance": "مالی",
                "users": "کاربران",
                "pharm_dashboard": "داشبورد",
                "pharm_finance": "مالی",
                "pharm_inventory": "موجودی",
                "pharm_sales": "فروش",
                "pharm_customers": "مشتریان",
                "pharm_suppliers": "تامين کنندگان",
                "pharm_loans": "قرضه ها",
                "pharm_reports": "گزارش‌ها",
                "pharm_price_check": "نرخ",
                "pharm_returns": "مرجوعی",
                "pharm_users": "کاربران",
                "pharm_settings": "تنظیمات",
                # Dashboard Cards
                "pharmacy_finance": "مالی داروخانه",
                "credit_controls": "کنترول قرضه",
                "user_management": "مدیریت کاربران",
                "inventory_stats": "آمار موجودی",
                "select_product_info": "برای مشاهده آمار، محصول را انتخاب کنید",
                # Common UI
                "name": "نام",
                "phone": "تلفن",
                "address": "آدرس",
                "email": "ایمیل",
                "date": "تاریخ",
                "status": "وضعیت",
                "actions": "عملیات",
                "amount": "مقدار",
                "balance": "موجودی",
                "paid": "پرداخت شده",
                "pending": "معلق",
                "type": "نوع",
                "notes": "یادداشت‌ها",
                "description": "توضیحات",
                "category": "دسته‌بندی",
                "batch_number": "شماره بچ",
                "expiry_date": "تاریخ انقضا",
                "purchase_price": "قیمت خرید",
                "sale_price": "قیمت فروش",
                "stock": "موجودی",
                "unit": "واحد",
                "medicine": "دارو",
                "days_left": "روز باقی",
                # Buttons
                "add_new": "افزودن جدید",
                "refresh": "بروزرسانی",
                "clear": "پاک کردن",
                "submit": "ارسال",
                "confirm": "تایید",
                "close": "بستن",
                "view": "مشاهده",
                "details": "جزئیات",
                "process": "پردازش",
                "pay": "پرداخت",
                "receive": "دریافت",
                "return": "برگشت",
                "reprint": "چاپ مجدد",
                # Finance
                "daily_report": "گزارش روزانه",
                "monthly_report": "گزارش ماهانه",
                "yearly_report": "گزارش سالانه",
                "overview": "نمای کلی",
                "income": "درآمد",
                "expenses": "هزینه‌ها",
                "profit": "سود",
                "net_profit": "سود خالص",
                "gross_sales": "فروش کل",
                "total_sales": "مجموع فروش",
                "total_orders": "مجموع سفارشات",
                "total_returns": "مجموع مرجوعی",
                "cash_received": "نقد دریافتی",
                "credit_given": "قرضه داده شده",
                # Inventory
                "add_product": "افزودن محصول",
                "edit_product": "ویرایش محصول",
                "low_stock_alert": "هشدار کمبود موجودی",
                "out_of_stock": "ناموجود",
                "in_stock": "موجود",
                "reorder_level": "سطح سفارش مجدد",
                # Sales
                "new_sale": "فروش جدید",
                "cart": "سبد",
                "subtotal": "جمع فرعی",
                "grand_total": "جمع کل",
                "payment_method": "روش پرداخت",
                "customer": "مشتری",
                "walk_in": "مستقیم",
                "bill_number": "شماره فاکتور",
                "invoice": "فاکتور",
                # Customers/Suppliers
                "add_customer": "افزودن مشتری",
                "add_supplier": "افزودن تامین کننده",
                "customer_name": "نام مشتری",
                "supplier_name": "نام تامین کننده",
                "contact": "تماس",
                "total_purchases": "مجموع خریدها",
                "total_due": "مجموع بدهی",
                # Loans
                "give_loan": "قرضه دادن",
                "receive_payment": "دریافت پرداخت",
                "loan_history": "تاریخچه قرضه",
                "outstanding": "معوقه",
                "loan_date": "تاریخ قرضه",
                "due_date": "تاریخ سررسید",
                # Reports
                "sales_report": "گزارش فروش",
                "inventory_report": "گزارش موجودی",
                "customer_report": "گزارش مشتریان",
                "expiry_report": "گزارش انقضا",
                "expiring_stock": "موجودی در حال انقضا",
                "expired": "منقضی شده",
                "alert": "هشدار",
                "active": "فعال",
                "print_report": "چاپ گزارش",
                "net_sales": "فروش خالص",
                "return_items_count": "اقلام مرجوعی",
                "transaction_details": "جزئیات تراکنش‌ها",
                "returned_items_details": "جزئیات اقلام مرجوعی",
                "credit_loan_info": "معلومات قرضه‌ها",
                "low_stock_medicines": "داروهای رو به اتمام",
                "medicine_expiry_status": "وضعیت انقضای دارو",
                "print_transactions": "🖨️ چاپ تراکنش‌ها",
                "print_loans": "🖨️ چاپ قرضه‌ها",
                "print_stock_report": "🖨️ چاپ راپور موجودی",
                "print_expiry_report": "🖨️ چاپ گزارش انقضا",
                "print_returns": "🖨️ چاپ راپور مرجوعی",
                "print_complete_pharmacy_report": "🖨️ چاپ راپور کامل داروخانه",
                "last_7_days": "۷ روز گذشته",
                "this_month": "این ماه",
                "today": "امروز",
                "expiring_within": "انقضا در",
                "days": "روز",
                "invoice_number_short": "نمبر بل",
                "batch_no_short": "نمبر بچ",
                "invoices_transactions": "بل‌ها / تراکنش‌ها",
                "pharmacy_loans_credit_details": "جزئیات قرضه‌های داروخانه",
                "critical_stock_alert": "هشدار جدی موجودی",
                "expiring_stock_report": "گزارش کالاهای در حال انقضا",
                "showing_items_expiring_within": "نمایش کالاهایی که منقضی می‌شوند در:",
                "report_period": "دوره گزارش",
                "generated_at": "ایجاد شده",
                "total_active_loans": "تعداد کل قرضه‌های فعال",
                "total_loan_amount": "مبلغ کل قرضه‌ها",
                "total_outstanding_balance": "مجموع باقیمانده",
                "total_items_monitored": "کل کالاهای بررسی شده",
                "already_expired_count": "قبلاً منقضی شده",
                "nearing_expiry": "نزدیک به انقضا",
                "total_transactions": "کل تراکنش‌ها",
                "total_items_sold": "کل کالاهای فروخته شده",
                "total_sales_amount": "مبلغ کل فروش",
                "total_low_stock_items": "تعداد کل کالاهای رو به اتمام",
                "complete_pharmacy_reports_summary": "خلاصه کامل گزارشات داروخانه",
                # Settings
                "company_info": "اطلاعات شرکت",
                "maintenance": "نگهداری",
                "backup": "پشتیبان‌گیری",
                "restore": "بازیابی",
                "company_name": "نام شرکت",
                "company_address": "آدرس شرکت",
                "company_phone": "تلفن شرکت",
                "language": "زبان",
                "theme": "تم",
                "dark_mode": "حالت تاریک",
                "light_mode": "حالت روشن",
                # Users
                "role": "نقش",
                "permissions": "مجوزها",
                "add_user": "افزودن کاربر",
                "edit_user": "ویرایش کاربر",
                "manager": "مدیر",
                "staff": "کارمند",
                # Returns
                "return_item": "برگشت کالا",
                "return_reason": "دلیل برگشت",
                "refund_amount": "مبلغ بازپرداخت",
                "original_bill": "فاکتور اصلی",
                # Messages
                "success": "موفق",
                "error": "خطا",
                "warning": "هشدار",
                "confirm_delete": "تایید حذف",
                "no_data": "داده‌ای موجود نیست",
                "loading": "در حال بارگذاری...",
                "customer_not_found": "اطلاعات مشتری یافت نشد",
                "payment_received": "پرداخت با موفقیت دریافت شد",
                "required": "الزامی",
                "and": "و",
                "name_contact_required": "نام و شماره تماس الزامی است",
                 "confirm_delete_supplier": "آیا از حذف این تامین کننده مطمئن هستید؟",
                 "remove": "حذف",
                 "confirm_remove_salary": "آیا می‌خواهید این تنظیمات معاش را حذف کنید؟",
                 "main_finance_notice": "تعیین معاش برای کاربران سیستم اصلی باید در بخش مالی اصلی انجام شود.",
                 "custom_range": "محدوده دلخواه",
                 "reprint_bill": "چاپ مجدد فاکتور",
                 "weekly_report": "گزارش هفته‌وار",
                 "weekly": "هفته‌وار",
                 "units": "واحدها",
                 "enter_reason": "دلیل را بنویسید",
                 "reason": "دلیل",
                 "select_quantity": "لطفاً مقدار را انتخاب کنید",
                 "account": "حساب",
                 "refund_mode": "حالت بازپرداخت",
                # Added Detailed Pharmacy Keys
                "pharmacy_financial_management": "مدیریت مالی داروخانه",
                "record_new_expense": "ثبت هزینه جدید",
                "daily_expense": "هزینه روزانه",
                "petty_cash": "پول نقد",
                "utility": "خدمات عمومی",
                "other": "دیگر",
                "description_of_expense": "شرح هزینه",
                "daily_total": "مجموع روزانه",
                "monthly_total": "مجموع ماهانه",
                "staff_salary_setup": "تنظیم معاش کارمندان",
                "select_staff": "انتخاب کارمند",
                "salary_type": "نوع معاش",
                "assign_salary": "تعیین معاش",
                "staff_name": "نام کارمند",
                "salary_configured_success": "معاش با موفقیت تنظیم شد",
                "gross_cogs": "ناخالص COGS",
                "net_cogs": "خالص COGS",
                "trading_profit": "سود تجاری",
                "opex": "مجموع هزینه‌های عملیاتی",
                "net_monthly_profit": "سود خالص ماهانه",
                "total_val": "ارزش کل",
                "cost": "قیمت",
                "brand": "برند",
                "company": "شرکت",
                "vendor": "فروشنده",
                "add_medicine": "افزودن دارو",
                "basket": "سبد خرید",
                "last_bill": "آخرین فاکتور #",
                "reprint_last_bill": "چاپ مجدد فاکتور",
                "method": "روش",
                "credit_sale_loan": "فروش قسطی (قرضه)",
                "process_checkout": "تکمیل خرید",
                "walk_in_customer": "مشتری عادی",
                "insufficient_stock": "کمبود موجودی",
                "limit_exceeded": "بیش از حد مجاز",
                "customer_info": "اطلاعات مشتری",
                "kyc_management": "مدیریت مشتری و KYC",
                "basic_info": "اطلاعات پایه",
                "contact_number": "شماره تماس",
                "allow_credit_sales": "اجازه فروش قسطی",
                "kyc_documentation": "اسناد KYC",
                "customer_photo": "عکس مشتری",
                "id_card_photo": "عکس تذکره",
                "browse": "انتخاب",
                "upload_method": "روش آپلود",
                "open_camera": "باز کردن کمره",
                "upload_photo": "آپلود عکس",
                "add_edit_supplier": "افزودن یا ویرایش تامین کننده",
                "monthly_close": "بستن ماهانه",
                "preset": "پیش‌فرض",
                "from": "از",
                "to": "تا",
                "price_check_placeholder": "برای مشاهده قیمت، محصول را اسکن کنید",
                "not_found": "محصول یافت نشد",
                "already_returned": "قبلاً مرجوع شده",
                "remaining": "باقیمانده",
                "refund_mode": "حالت بازپرداخت",
                "fully_returned": "کامل مرجوع شده",
                "show_passwords": "نمایش رمزها",
                "hide_passwords": "پنهان کردن رمزها",
                "assigned_features": "بخش‌های اختصاص داده شده",
                "whatsapp_integration": "اتصال به واتساپ",
                "offline_mode": "فعال سازی حالت آفلاین",
                "optimize_database": "بهینه‌سازی دیتابیس",
                "clear_logs": "پاکسازی گزارشات",
                "full_backup": "تهیه نسخه پشتیبان کامل",
                "invoice_not_found": "فاکتور یافت نشد",
                "for": "برای",
                "product": "محصول",
                "return_quantity": "تعداد مرجوعی",
                "camera_error": "خطای کمره",
                "resumed": "دوباره شروع شد",
                "sale_transaction_resumed": "تراکنش فروش دوباره شروع شد.",
                "invalid_qty": "تعداد نامعتبر",
                "qty_cannot_be_negative": "تعداد نمی‌تواند منفی باشد.",
                "sale_completed": "فروش تکمیل شد",
                "bill_printed_successfully": "فاکتور با موفقیت چاپ شد!",
                "print_error": "خطای چاپ",
                "failed_to_generate_bill": "خطا در ایجاد فاکتور.",
                "failed_to_print_bill": "خطا در چاپ فاکتور",
                "no_bills": "فاکتوری نیست",
                "no_bills_found_to_reprint": "فاکتوری برای چاپ مجدد یافت نشد",
                "no_records": "ریکارد موجود نیست",
                "no_kyc_found": "اسنادی برای این مشتری یافت نشد.",
                "successfully_returned": "با موفقیت مرجوع شد",
                "items": "قلم کالا",
                "refund": "بازپرداخت",
                "no_sale_found_with_invoice": "فروشی با این فاکتور یافت نشد",
                "ready_to_scan": "آماده سکین",
                "scan": "سکین"
            },
        }

    @classmethod
    def get_instance(cls):
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def set_language(self, lang):
        if lang in self.translations:
            self.current_lang = lang
            self.language_changed.emit(lang)

    def get(self, key):
        return self.translations.get(self.current_lang, self.translations["en"]).get(key, key)

    def is_rtl(self):
        return self.current_lang in ["ps", "dr"]

    def localize_digits(self, text):
        if self.current_lang == "en":
            return str(text)
        
        digits_map = {
            '0': '۰', '1': '۱', '2': '۲', '3': '۳', '4': '۴',
            '5': '۵', '6': '۶', '7': '۷', '8': '۸', '9': '۹'
        }
        
        return "".join(digits_map.get(c, c) for c in str(text))

lang_manager = Localization.get_instance()
